### ISSUE TITLE
Add thumbnail assets to production collections

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-data#143]
## What
We now have a bucket in MCP `s3://veda-thumbnails` that is publicly accessible via cloudfront `https://thumbnails.openveda.cloud/`. Update production collection metadata to include these thumbnails as assets to improve the browser experience.

### Parent issues
#124 #122

## Notes
For a first pass at improving our browser experience we can use exactly the same thumbnails that are configured in the dashboard for our STAC collections. The thumbnails from veda-config/datasets have already been copied to the thumbnail bucket but the thumbnails in eic-config have not (there is a large amount of overlap, probably only the climdex-* thumbnails need to be copied to the thumbnail bucket.

For a collection in s3, you can identify the dataset name by searching the collection id in veda-config and using the data.mdx file to identify the appropriate thumbnail. Veda-config groups datasets so in this first pass some of our collections will have duplicate thumbnails.

### Config mdx example
For the [hls-events.ej.data.mdx](https://github.com/NASA-IMPACT/veda-config/blob/develop/datasets/hls-events.ej.data.mdx?plain=1#L24) configuration, the thumbnail `hls-events-ej--dataset-cover.png` is located in media attributes.
```
---
id: hls_events
name: 'Harmonized Landsat Sentinel-2 (Selected Events)'
description: '30-meter resolution harmonized Landsat 8/9 and Sentinel-2A/B data products'
usage:
  - url: "https://nasa-impact.github.io/veda-docs/notebooks/quickstarts/hls-visualization.html"
    label: View example notebook
    title: 'Multi-Band Visualization Preview for Harmonized Landsat Sentinel-2 (HLS)'
  - url: "https://nasa-veda.2i2c.cloud/hub/user-redirect/git-pull?repo=https://github.com/NASA-IMPACT/veda-docs&urlpath=lab/tree/veda-docs/notebooks/quickstarts/hls-visualization.ipynb&branch=main"
    label: Run example notebook
    title: 'Multi-Band Visualization Preview for Harmonized Landsat Sentinel-2 (HLS)'
media:
  src: ::file ./hls-events-ej--dataset-cover.png
  alt: 2017 harmonized Landsat 8 shortwave infrared (SWIR) false color composite image that provides enhanced contrast to detect flood extent.
  <SNIP>
layers:
  - id: hls-l30-002-ej
    stacCol: hls-l30-002-ej-reprocessed
    name: HLS Landsat SWIR
<SNIP>
```

### STAC Collection metadata example
Thumbnail objects are added to the `assets` property of a collection with the key `thumbnail`. If a collection does not already have an assets. See https://test.openveda.cloud/api/stac/collections/hls-l30-002-ej-reprocessed for an example of a collection with a thumbnail asset.
```
"assets": {
    "thumbnail": {
        "title": "Thumbnail",
        "href": "https://thumbnails.openveda.cloud/<dataset-name>.png",
        "type": "image/png",
        "roles": ["thumbnail"]
    },
   "someotherasset": {
        "title": "Name of an asset",
        "href": "somewhere.com",
        "roles": ["datal"]
    }
}
```

### veda-configs
- [veda-config/datasets](https://github.com/NASA-IMPACT/veda-config/tree/main/datasets)
- [veda-config-eic/datasets](https://github.com/NASA-IMPACT/veda-config-eic/tree/main/datasets)

## AC
- [x] thumbnails from veda-config datasets uploaded to `s3://veda-thumbnails`
- [x] eic-only thumbnails from eic config uploaded to `s3://veda-thumbnails`
- [x] BONUS `landsat-c2l2-sr-*` thumbnails identified 
- [x] Landsat thumbnails resized (if needed) and uploaded to `s3://veda-thumbnails` 
- [x] production collection metadata updated to include thumbnail assets in veda-data and published to production catalog
